'use server';

import { ai } from '@/app/ai/genkit';
import { z } from 'zod';
import { GenerateRequest } from 'genkit/generate';

const ImageGenerationInputSchema = z.object({
  prompt: z.string().describe('The text prompt to generate an image from.'),
  initialImage: z.string().optional().describe("An optional initial image as a data URI."),
});
export type ImageGenerationInput = z.infer<typeof ImageGenerationInputSchema>;

const ImageGenerationOutputSchema = z.object({
  imageUrl: z.string().describe('The data URI of the generated image.'),
});
export type ImageGenerationOutput = z.infer<typeof ImageGenerationOutputSchema>;

export async function imageGeneration(input: ImageGenerationInput): Promise<ImageGenerationOutput> {
  return imageGenerationFlow(input);
}

const imageGenerationFlow = ai.defineFlow(
  {
    name: 'imageGenerationFlow',
    inputSchema: ImageGenerationInputSchema,
    outputSchema: ImageGenerationOutputSchema,
  },
  async ({ prompt, initialImage }) => {
    if (!process.env.GEMINI_API_KEY) {
        throw new Error("API key not valid. Please set the GEMINI_API_KEY environment variable.");
    }
    
    let request: GenerateRequest;

    if (initialImage) {
      // Image-to-image generation
      request = {
        model: 'googleai/gemini-2.5-flash-image-preview',
        prompt: [
          { media: { url: initialImage } },
          { text: prompt },
        ],
        config: {
          responseModalities: ['IMAGE'],
        },
      };
    } else {
      // Text-to-image generation
      request = {
        model: 'googleai/imagen-4.0-fast-generate-001',
        prompt: prompt,
      };
    }

    const { media } = await ai.generate(request);

    if (!media || !media.url) {
      throw new Error('No image was generated by the model.');
    }

    return {
      imageUrl: media.url,
    };
  }
);
